# Generated by Django 5.2.1 on 2025-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Токен для верификации', max_length=100, null=True, verbose_name='Токен'),
        ),
    ]
