# Generated by Django 5.2.1 on 2025-06-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/image', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=False, help_text='Отметьте, если товар есть в наличии', verbose_name='Наличие товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Указывается дата и время создания товара', verbose_name='Дата создания карточки товара')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Указывается дата и время обновления данных о товаре', verbose_name='Дата обновления карточки товара')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name', 'category', 'price'],
            },
        ),
    ]
