# Generated by Django 5.2 on 2025-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Вводится дата и время обновления данных о товаре",
                verbose_name="Дата обновления карточки товара",
            ),
        ),
    ]
