# Generated by Django 5.2.1 on 2025-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар есть в наличии', verbose_name='Наличие товара'),
        ),
    ]
